services:
  jenkins:
    volumes:
      - './data/jenkins_home:/var/jenkins_home'
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "50000:50000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jenkins.rule=Host(`jenkins.labzs.com`)"
      - "traefik.http.routers.jenkins.entrypoints=web"
      - "traefik.http.services.jenkins.loadbalancer.server.port=8080"
    networks:
      - proxy

networks:
  proxy:
    external: true

